In [40]:
import numpy as np


In [41]:
def numerical_derivative(f,x):
  # 델타 x 값 정의 lim에 해당되는 작은 값
  delta_x=1e-4
  return (f(x+delta_x)-f(x-delta_x))/(2*delta_x)

In [42]:
def my_func1(x):
  return x**2

In [43]:
result=numerical_derivative(my_func1,3)
print("result==",result)

result== 6.000000000012662


In [44]:
def my_func2(x):
  return x**2+2*x+1
# x**2+2*x+1 = 9
# 미분시 2x+2=6
result=numerical_derivative(my_func2,3)
print(result)

8.000000000016882


In [45]:
def numerical_derivative2(f,x):
  delta_x=1e-4
  grad=np.zeros_like(x)
  print('x:',x)
  print('grad:',grad)

  it=np.nditer(x,flags=['multi_index'], op_flags=['readwrite'])

  while not it.finished:
    idx=it.multi_index
    print('idx:',idx,'x[idx]:',x[idx])
    tmp_val=x[idx]
    x[idx]=float(tmp_val)+delta_x
    fx1=f(x)
    x[idx]=tmp_val-delta_x
    fx2=f(x)

    grad[idx]=(fx1-fx2)/(2*delta_x)
    print('grad[idx]:',grad[idx])
    print('grad',grad)

    x[idx]=tmp_val
    it.iternext()

  return grad

In [46]:
def func1(input):
  x=input[0]
  y=input[1]
  return (2*x + 3*x*y + np.power(y,3))


In [47]:
numerical_derivative2(func1, np.array([3.0, 2.0]))

x: [3. 2.]
grad: [0. 0.]
idx: (0,) x[idx]: 3.0
grad[idx]: 7.999999999999119
grad [8. 0.]
idx: (1,) x[idx]: 2.0
grad[idx]: 21.000000010040765
grad [ 8.         21.00000001]


array([ 8.        , 21.00000001])

In [48]:
def func2(input):
  w=input[0][0]
  x=input[0][1]
  y=input[1][0]
  z=input[1][1]

  return (w*x + x*y*z + 3*w + z**2)

In [49]:
numerical_derivative2(func2,np.array([[1.0,2.0],[3.0,4.0]]))

x: [[1. 2.]
 [3. 4.]]
grad: [[0. 0.]
 [0. 0.]]
idx: (0, 0) x[idx]: 1.0
grad[idx]: 5.000000000023874
grad [[5. 0.]
 [0. 0.]]
idx: (0, 1) x[idx]: 2.0
grad[idx]: 13.00000000000523
grad [[ 5. 13.]
 [ 0.  0.]]
idx: (1, 0) x[idx]: 3.0
grad[idx]: 7.999999999981355
grad [[ 5. 13.]
 [ 8.  0.]]
idx: (1, 1) x[idx]: 4.0
grad[idx]: 14.000000000002899
grad [[ 5. 13.]
 [ 8. 14.]]


array([[ 5., 13.],
       [ 8., 14.]])

In [51]:
numerical_derivative2(my_func1,np.array([3]))

x: [3]
grad: [0]
idx: (0,) x[idx]: 3
grad[idx]: 25000
grad [25000]


array([25000])