In [89]:
import torch
import torch.nn as nn
torch.manual_seed(777)

In [90]:
x=torch.FloatTensor([[0,0],[0,1],[1,0],[1,1]])
y=torch.FloatTensor([[0],[0],[0],[1]])

model=nn.Sequential(nn.Linear(2,1),nn.Sigmoid())

In [91]:
criterion=torch.nn.BCELoss()
optimizer=torch.optim.SGD(model.parameters(), lr=1)




In [92]:
for epoch in range(1001):
  h_hat=model(x)
  cost=criterion(h_hat,y)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('epoch:{}, cost:{}'.format(epoch,cost.item()))

epoch:0, cost:0.6932064294815063
epoch:100, cost:0.14414836466312408
epoch:200, cost:0.0817771703004837
epoch:300, cost:0.05658476799726486
epoch:400, cost:0.04307378828525543
epoch:500, cost:0.03469350188970566
epoch:600, cost:0.029005466029047966
epoch:700, cost:0.024899723008275032
epoch:800, cost:0.021800503134727478
epoch:900, cost:0.01938023790717125
epoch:1000, cost:0.01743890717625618


In [93]:
with torch.no_grad():
  pred=model(x)
  predicted=(pred>0.5).float()

print(pred)
print(predicted)



tensor([[1.2462e-05],
        [2.0246e-02],
        [2.0246e-02],
        [9.7164e-01]])
tensor([[0.],
        [0.],
        [0.],
        [1.]])


In [94]:
model=nn.Sequential(nn.Linear(2,10, bias=True),nn.Sigmoid(),
                    nn.Linear(10,10, bias=True),nn.Sigmoid(),
                    nn.Linear(10,10),
                    nn.Linear(10,1,bias=True),nn.Sigmoid())


In [95]:
criterion1=torch.nn.BCELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=1)


In [96]:
for epoch in range(10001):
  h_hat=model(x)
  cost=criterion1(h_hat,y)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('epoch:{},cost:{}'.format(epoch,cost.item()))

epoch:0,cost:0.673554539680481


epoch:100,cost:0.17558470368385315
epoch:200,cost:0.0030957814306020737
epoch:300,cost:0.0009294991614297032
epoch:400,cost:0.0005110654747113585
epoch:500,cost:0.0003430704236961901
epoch:600,cost:0.00025452752015553415
epoch:700,cost:0.0002005162968998775
epoch:800,cost:0.00016443940694443882
epoch:900,cost:0.00013875158037990332
epoch:1000,cost:0.000119639458716847
epoch:1100,cost:0.00010488509724382311
epoch:1200,cost:9.317811782239005e-05
epoch:1300,cost:8.370212890440598e-05
epoch:1400,cost:7.586622086819261e-05
epoch:1500,cost:6.929102528374642e-05
epoch:1600,cost:6.371623021550477e-05
epoch:1700,cost:5.8906065532937646e-05
epoch:1800,cost:5.473384590004571e-05
epoch:1900,cost:5.10888421558775e-05
epoch:2000,cost:4.787264333572239e-05
epoch:2100,cost:4.499437636695802e-05
epoch:2200,cost:4.2429513996466994e-05
epoch:2300,cost:4.015810918645002e-05
epoch:2400,cost:3.807455868809484e-05
epoch:2500,cost:3.619556810008362e-05
epoch:2600,cost:3.448009738349356e-05
epoch:2700,cost:3.2

In [98]:
with torch.no_grad():
  pred=model(x)
  predicted=(pred> 0.5). float()

  print(predicted)


tensor([[0.],
        [0.],
        [0.],
        [1.]])


In [100]:
# 그냥 해보세용
x=torch.FloatTensor([[0,0],[0,1],[1,0],[1,1]])
y=torch.FloatTensor([[1],[1],[1],[0]])