In [35]:
import torch
# 이미지데이터를 사용하기 위해서 기존 데이터 사용, 변형
import torchvision.datasets as dataset
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torch.nn as nn
import matplotlib.pyplot as plt
import random
import torch.optim as optim
import torch.nn.functional as F

In [36]:
input=torch.Tensor(1,1,28,28) #배치사이즈 (sample 수, 채널, 높이 , 너비)
input

tensor([[[[ 2.2687e+18,  6.8103e-43,  1.6947e+09,  6.8103e-43,  1.2343e+19,
            6.8103e-43,  1.6947e+09,  6.8103e-43,  3.5821e+20,  6.8103e-43,
            1.6947e+09,  6.8103e-43,  1.1224e+19,  6.8103e-43,  1.6947e+09,
            6.8103e-43,  3.5820e+20,  6.8103e-43,  1.6947e+09,  6.8103e-43,
            3.5815e+20,  6.8103e-43,  1.6947e+09,  6.8103e-43,  3.5809e+20,
            6.8103e-43,  1.6947e+09,  6.8103e-43],
          [ 3.5805e+20,  6.8103e-43,  1.6947e+09,  6.8103e-43,  3.5807e+20,
            6.8103e-43,  1.6947e+09,  6.8103e-43,  3.5836e+20,  6.8103e-43,
            1.6947e+09,  6.8103e-43,  3.5808e+20,  6.8103e-43,  1.6947e+09,
            6.8103e-43,  3.5807e+20,  6.8103e-43,  1.6947e+09,  6.8103e-43,
            3.5802e+20,  6.8103e-43,  1.6947e+09,  6.8103e-43,  3.5811e+20,
            6.8103e-43,  1.6947e+09,  6.8103e-43],
          [ 3.5838e+20,  6.8103e-43,  1.6947e+09,  6.8103e-43,  3.5814e+20,
            6.8103e-43,  1.6947e+09,  6.8103e-43,  3.5812e+20,

In [37]:
conv1=nn.Conv2d(1,32,3,padding=1)
# channel, output_channel , kernel_size, padding
print(conv1)

Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


In [38]:
conv2=nn.Conv2d(32,64, kernel_size=3, padding=1)
print(conv2)

Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


In [39]:
pool=nn.MaxPool2d(2)
print(pool)

MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)


In [40]:
out1=conv1(input) #[1,1,28,28]
print(out1.size())
out2=pool(out1)
print(out2.size())

torch.Size([1, 32, 28, 28])
torch.Size([1, 32, 14, 14])


In [41]:
out3=conv2(out2)
print(out3.size())
out4=pool(out3)
print(out4.size)

torch.Size([1, 64, 14, 14])
<built-in method size of Tensor object at 0x000001E6619D6C10>


In [42]:
out5 = out4.view(out4.size(0), -1) # -1 나머지 차원을 다 곱함 -> 64 * 7 * 7
print('out5 : ', out5.size())

out5 :  torch.Size([1, 3136])


In [44]:
fc=nn.Linear(3136,10)
out6=fc(out5)
print(out6.size())
print(out6)
print(out6.argmax(dim=1))

torch.Size([1, 10])
tensor([[ 2.3249e+19,  1.8703e+19,  1.6887e+19, -2.2163e+19, -3.9978e+19,
         -3.4829e+19,  1.3237e+19, -5.6067e+19, -4.0343e+19, -3.1268e+19]],
       grad_fn=<AddmmBackward0>)
tensor([0])
