In [61]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [62]:
torch.manual_seed(1)
# 변수 선언   
x_train=torch.FloatTensor([[1],[2],[3],[4],[5]])
y_train=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [63]:
model=nn.Linear(1,1)
# input_dim, output_dim
print(list(model.parameters()))


[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [64]:
# SGD-확률적 경사하강법 lr 러닝데이터
optimizer=optim.SGD(model.parameters(),lr=0.01)


In [65]:
for epoch in range(20001):
  predict=model(x_train)
  # error의 제곱으로 손실
  cost=F.mse_loss(predict,y_train)

  optimizer.zero_grad()
  # 초기화
  cost.backward()
  optimizer.step()

  if epoch % 100==0:
    print('Epoch=',epoch,'Cost=',cost.item())
  

Epoch= 0 Cost= 39.16685104370117
Epoch= 100 Cost= 0.08463062345981598
Epoch= 200 Cost= 0.04298952594399452
Epoch= 300 Cost= 0.021837208420038223
Epoch= 400 Cost= 0.01109258271753788
Epoch= 500 Cost= 0.00563468411564827
Epoch= 600 Cost= 0.0028622171375900507
Epoch= 700 Cost= 0.0014539161929860711
Epoch= 800 Cost= 0.0007385412463918328
Epoch= 900 Cost= 0.00037515218718908727
Epoch= 1000 Cost= 0.00019056595920119435
Epoch= 1100 Cost= 9.680409129941836e-05
Epoch= 1200 Cost= 4.91717473778408e-05
Epoch= 1300 Cost= 2.497919740562793e-05
Epoch= 1400 Cost= 1.2689983122982085e-05
Epoch= 1500 Cost= 6.447205578297144e-06
Epoch= 1600 Cost= 3.276181814726442e-06
Epoch= 1700 Cost= 1.6654261116855196e-06
Epoch= 1800 Cost= 8.460160643153358e-07
Epoch= 1900 Cost= 4.302897309571563e-07
Epoch= 2000 Cost= 2.1860606125301274e-07
Epoch= 2100 Cost= 1.1113379372318377e-07
Epoch= 2200 Cost= 5.657594925878584e-08
Epoch= 2300 Cost= 2.86554158179797e-08
Epoch= 2400 Cost= 1.4702209227834828e-08
Epoch= 2500 Cost= 7.

In [66]:
print(list(model.parameters()))

[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [67]:
model(torch.FloatTensor([[7],[9]]))
# t

tensor([[15.0000],
        [19.0000]], grad_fn=<AddmmBackward0>)

In [71]:
class LinearRegressionModel(nn.Module):
  def __init__(self): #모델 정의 
    super().__init__()
    self.linear=nn.Linear(1,1)

    # 실행
  def forward(self,x):
    return self.linear(x)

In [72]:
model=LinearRegressionModel()
optimizer=optim.SGD(model.parameters(),lr=0.01)

In [73]:
for epoch in range(20001):
  prediction=model(x_train)
  cost=F.mse_loss(prediction,y_train)

  optimizer.zero_grad()
  cost.backward()

  optimizer.step()

  if epoch % 400 ==0:
    print('Epoch',epoch,'cost',cost)

Epoch 0 cost tensor(102.3972, grad_fn=<MseLossBackward0>)
Epoch 400 cost tensor(0.0018, grad_fn=<MseLossBackward0>)
Epoch 800 cost tensor(0.0001, grad_fn=<MseLossBackward0>)
Epoch 1200 cost tensor(7.9607e-06, grad_fn=<MseLossBackward0>)
Epoch 1600 cost tensor(5.3039e-07, grad_fn=<MseLossBackward0>)
Epoch 2000 cost tensor(3.5386e-08, grad_fn=<MseLossBackward0>)
Epoch 2400 cost tensor(2.4144e-09, grad_fn=<MseLossBackward0>)
Epoch 2800 cost tensor(1.8708e-10, grad_fn=<MseLossBackward0>)
Epoch 3200 cost tensor(7.6443e-11, grad_fn=<MseLossBackward0>)
Epoch 3600 cost tensor(7.6443e-11, grad_fn=<MseLossBackward0>)
Epoch 4000 cost tensor(7.6443e-11, grad_fn=<MseLossBackward0>)
Epoch 4400 cost tensor(7.6443e-11, grad_fn=<MseLossBackward0>)
Epoch 4800 cost tensor(7.6443e-11, grad_fn=<MseLossBackward0>)
Epoch 5200 cost tensor(7.6443e-11, grad_fn=<MseLossBackward0>)
Epoch 5600 cost tensor(7.6443e-11, grad_fn=<MseLossBackward0>)
Epoch 6000 cost tensor(7.6443e-11, grad_fn=<MseLossBackward0>)
Epoch 6