In [2]:
import torch

In [3]:
print(torch.tensor([1,2,3,4,5]))
print(torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64))
print(torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)) 

tensor([1, 2, 3, 4, 5])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
ft=torch.FloatTensor([[1,2,3],[4,5,6]]);print(ft)
lt=torch.FloatTensor([[1,2,3],[4,5,6]]);print(lt)
bt=torch.FloatTensor([[1,0],[0,1]]);print(bt)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 0.],
        [0., 1.]])


In [7]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
# np배열 생성
print(x,type(x),x.shape)


[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [8]:
tx=torch.from_numpy(x)
print(tx,type(tx),tx.shape,tx.size())
# pytorch 텐서(데이터 형태)생성


tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32) <class 'torch.Tensor'> torch.Size([2, 3]) torch.Size([2, 3])


In [12]:
nx=tx.numpy()
print(nx,type(nx),nx.shape)
# numpy는 size() 사용불가

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [14]:
print(ft,ft.long())
# long형으로 형변환 ft.long()
print(lt,lt.float())
# float()형으로 형변환
print (bt,bt.long())



tensor([[1., 2., 3.],
        [4., 5., 6.]]) tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]]) tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 0.],
        [0., 1.]]) tensor([[1, 0],
        [0, 1]])


In [23]:
x=torch.tensor([[[1,2],[3,4],[5,6],[7,8],[9,10],[11,12,]]])
x

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [29]:
print(x.shape)
print(x.size())
# x의 차원계수
print('x.dim',x.dim())
# x의 사이즈 len
print('len(x.size())',len(x.size()))
print(x.size(0))
print(x.shape[0])
print(x.size(1))
print(x.shape[1])
print(x.size(2))
print(x.shape[2])
# 마지막위치 -1(리버스)
print(x.size(-1))
print(x.shape[-1])


torch.Size([1, 6, 2])
torch.Size([1, 6, 2])
x.dim 3
len(x.size()) 3
1
1
6
6
2
2
2
2


In [33]:
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[3,3]])


In [37]:
print('a+b:',a+b)
print('a-b:',a-b)
print('a*b:',a*b)
print('a/b:',a/b)
print('a//b:',a//b)
print('a==b:',a==b)
print('a!=b:',a!=b)
print('a**b:',a**b)


a+b: tensor([[3., 4.],
        [6., 7.]])
a-b: tensor([[-1.,  0.],
        [ 0.,  1.]])
a*b: tensor([[ 2.,  4.],
        [ 9., 12.]])
a/b: tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])
a//b: tensor([[0., 1.],
        [1., 1.]])
a==b: tensor([[False,  True],
        [ True, False]])
a!=b: tensor([[ True, False],
        [False,  True]])
a**b: tensor([[ 1.,  4.],
        [27., 64.]])


In [40]:
print(a)
print(a+1)
# 요소가 다르면 오류티비
print(a+torch.tensor([1,2]))


tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 3.],
        [4., 5.]])
tensor([[2., 4.],
        [4., 6.]])


In [42]:
print(a)
print(a.mul_ (b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


In [44]:
print(b)
print(b.sum())
print(b.sum(dim=0))
print(b.sum(dim=1))
print(b.mean())


tensor([[2., 2.],
        [3., 3.]])
tensor(10.)
tensor([5., 5.])
tensor([4., 6.])
tensor(2.5000)


In [47]:
x=np.arange(1,13).reshape(3,2,2)
# 3차원 tensor
tx=torch.from_numpy(x)

In [52]:
print(tx.view(3,4))
print(tx.view(2,3,2))
# -1은 모양을 잘 모를때
print(tx.view(3,-1))
print(tx.view(-1,3))


tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)


In [54]:
xx=tx.view(3,1,4)
xx

tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]], dtype=torch.int32)

In [56]:
x1=tx.view(3,1,4)
x2=tx.view(1,2,3,2)
# 차원제거
print(x1.squeeze())
print(x2.squeeze())

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]], dtype=torch.int32)


In [59]:
print(x1.size())
# 차원삽입
x1.unsqueeze(1)
x1.size()

torch.Size([3, 1, 4])


torch.Size([3, 1, 4])

In [71]:
# 3차원중 1번째 요소
print(tx[0])
# 3차원요소 1번째, 전부
print(tx[0,:])

print(tx[0,:,:])

print(tx[0,1,:])

print(tx[0,:,1])

print(tx[-1,:])


tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([3, 4], dtype=torch.int32)
tensor([2, 4], dtype=torch.int32)
tensor([[ 9, 10],
        [11, 12]], dtype=torch.int32)


In [76]:
# 텐서 자르기 split

# x=torch.FloatTensor(10,4)
# x 정수화
x=torch.arange(1,41).view(10,4)
# 스플릿 크기 4 dim=0은 2차원인데 크기 4로 자른다
splits=x.split(4,dim=0)
for s in splits:
  print(s.size())


torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [80]:
x1=torch.arange(1,41).view(4,10)
splits1=x1.split(3,dim=1)
for s in splits1:
  print(s.size())

torch.Size([4, 3])
torch.Size([4, 3])
torch.Size([4, 3])
torch.Size([4, 1])


In [81]:
# chunks
# 몇개의 구역으로 자를건지
chunks=x.chunk(2,dim=0)

for c in chunks:
  print(c.size())

torch.Size([5, 4])
torch.Size([5, 4])


In [87]:
# index_select
indice=torch.LongTensor([5,2])
# x.index_select(dim=0,index=indice)
y=x.index_select(dim=0,index=indice)
print(x)
print(y)


tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36],
        [37, 38, 39, 40]])
tensor([[21, 22, 23, 24],
        [ 9, 10, 11, 12]])


In [89]:
# Concatenate()
c=torch.cat([a,b],dim=1)
c

tensor([[ 2.,  4.,  2.,  2.],
        [ 9., 12.,  3.,  3.]])

In [93]:
# stack()
d=torch.stack([a,b])
print(d)
print(d.size())
print(a.size())
print(b.size())

tensor([[[ 2.,  4.],
         [ 9., 12.]],

        [[ 2.,  2.],
         [ 3.,  3.]]])
torch.Size([2, 2, 2])
torch.Size([2, 2])
torch.Size([2, 2])


In [96]:
# stack()
aa=a.view(2,1,2)
print(aa)
print(aa.size())
y=aa.expand(2,3,2)
y

tensor([[[ 2.,  4.]],

        [[ 9., 12.]]])
torch.Size([2, 1, 2])


tensor([[[ 2.,  4.],
         [ 2.,  4.],
         [ 2.,  4.]],

        [[ 9., 12.],
         [ 9., 12.],
         [ 9., 12.]]])

In [99]:
y1=torch.cat([aa]*3,dim=1)
y1

tensor([[[ 2.,  4.],
         [ 2.,  4.],
         [ 2.,  4.]],

        [[ 9., 12.],
         [ 9., 12.],
         [ 9., 12.]]])

In [101]:
# n까지 랜덤 수열 생성
x=torch.randperm(10).view(-1,5,5)
# 다차원으로 생성가능
x

tensor([6, 4, 8, 9, 0, 5, 2, 3, 1, 7])

In [104]:
#argmax
# 3**3사이의 랜덤 수열
x=torch.randperm(3**3).view(3,3,-1)
x

tensor([[[23, 17, 15],
         [25, 22, 20],
         [13,  1,  7]],

        [[18,  3, 26],
         [12,  5,  2],
         [ 4, 14, 21]],

        [[24, 11,  8],
         [ 6, 16, 19],
         [ 0,  9, 10]]])

In [107]:
y=x.argmax(dim=-1)
print(y)
print(y.size())


tensor([[0, 0, 0],
        [2, 0, 2],
        [0, 2, 2]])
torch.Size([3, 3])


In [110]:
# 1차원에서 가장 큰 k개의 값과 index 반환
value,indices=torch.topk(x,k=2,dim=-1)
print(value)
print(indices)
print(indices.size())


tensor([[[23, 17],
         [25, 22],
         [13,  7]],

        [[26, 18],
         [12,  5],
         [21, 14]],

        [[24, 11],
         [19, 16],
         [10,  9]]])
tensor([[[0, 1],
         [0, 1],
         [0, 2]],

        [[2, 0],
         [0, 1],
         [2, 1]],

        [[0, 1],
         [2, 1],
         [2, 1]]])
torch.Size([3, 3, 2])


In [117]:
# 마스크 true에 원하는 value 값
mask=x>10
print(mask)
y=x.masked_fill(mask,value=0)
print(y)


tensor([[[ True,  True,  True],
         [ True,  True,  True],
         [ True, False, False]],

        [[ True, False,  True],
         [ True, False, False],
         [False,  True,  True]],

        [[ True,  True, False],
         [False,  True,  True],
         [False, False, False]]])
tensor([[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  1,  7]],

        [[ 0,  3,  0],
         [ 0,  5,  2],
         [ 4,  0,  0]],

        [[ 0,  0,  8],
         [ 6,  0,  0],
         [ 0,  9, 10]]])


In [119]:
# 기본적으로 사용할 (유용한) 함수들 ones,zeros, ones_like, zeros_like 
print(torch.ones(2,3))
print(torch.zeros(2,3))
print(torch.ones(2,3))
print(torch.ones_like(a))
print(torch.zeros_like(a))


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
